### ISSUE TITLE
Bump to PHP 8.2 and Symfony 7

### ISSUE THREAD

**Issue by tacman** [yann-eugone/presta-sitemap-test-project#6]
Now that 4.0 is out, it'd be great to see this project on the latest version of PHP and Symfony.

I can submit a PR if you'd like.

**Comment by yann-eugone** [comment]
Sure, I'd be glad to merge it

**Comment by tacman** [comment]
OK, my branch now _mostly_ works with Symfony 7.  It was more work than I expected!  

* entity and controllers updated to use attributes rather than annotations
* fakerphp, since original faker is abandoned and didn't work with php 8.3
* sensio framework dropped, since Symfony now handles everything.
* Sitemaps now listed on home page for easier debugging
* Switch to sqlite database by default, so installation is easier.

Outstanding issues:

* the default route priority needs to change in the _bundle_, as sitemap*.xml should have a higher priority than anything else.  Otherwise, /{slug} is matched because application routes are higher priority than bundle routes.  Hack for now is to add a priority to the page route, but that's not very elegant.
* the xml and yml routes don't work, not sure why we'd want to use FileBinaryResponse.

To install

```bash
git clone --branch tac https://github.com/tacman/presta-sitemap-test-project
cd presta-sitemap-test-project
composer install
bin/console doctrine:database:create
bin/console doctrine:schema:update --force --complete
bin/console doctrine:fixtures:load --no-interaction
symfony server:start -d
symfony open:local
```

**Comment by yann-eugone** [comment]
Are you waiting for something on my side, so you can open a PR ?

**Comment by tacman** [comment]
Happy to open a PR, but it's not quite working for me yet.  What is the intention of the yaml and xml controllers?  Why do they need to be a binary response?

**Comment by yann-eugone** [comment]
Just got merged
